{
 "title": "Impfzeugs",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "siedlungsgebiet",
    "label": "siedlungsgebiet",
    "query": "1, 5, 10, 12, 15, 20, 30, 40, 50"
   },
   {
    "name": "bev_dichte",
    "label": "bev_dichte",
    "query": "5, 20, 30, 50, 70, 100, 130, 170, 200, 250, 300, 400, 500, 600, 800, 1000, 2000, 3000, 4000 "
   }
  ]
 },
 "panels": [
  {
   "title": "Inzidenzen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inzidenz: Links vs Rechts",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 18, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"rechts\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_svp + gp.wahl_rechtsparteien) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) < (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"links\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_sp + gp.wahl_gps) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) >= (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Anzahl \"Linke\" und \"Rechte\" Gemeinden",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  count(distinct gi.bfs_nummer) AS \"rechts\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_svp + gp.wahl_rechtsparteien) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) <  (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  count(distinct gi.bfs_nummer) AS \"links\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_sp + gp.wahl_gps) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) >= (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Anzahl Einwohner in \"Linken\" und \"Rechten\" Gemeinden",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  sum(gp.bevoelkerung_einwohner) AS \"rechts\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_svp + gp.wahl_rechtsparteien) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) <  (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  sum(gp.bevoelkerung_einwohner) AS \"links\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND (gp.wahl_sp + gp.wahl_gps) > 30\n  AND (gp.wahl_sp + gp.wahl_gps) >= (gp.wahl_svp + gp.wahl_rechtsparteien)\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Inzidenz: Haushaltsgrösse",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"unter\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.haushalt_haushaltsgroesse_pro_person < 2.4\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"uber\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.haushalt_haushaltsgroesse_pro_person > 2.4\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Inzidenz: Siedlungsfläche",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"unter\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.flaeche_siedlung < 12\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"uber\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.flaeche_siedlung > 12\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Impfquote",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacme: Anmeldungen, Erst und Zweit Impfungen",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(erstimpfung,$__interval),\n  count(erstimpfung) AS \"erst\"\nFROM gemeinde_impfungen\nWHERE\n  1=1\n  AND $__timeFilter(erstimpfung)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(zweitimpfung,$__interval),\n  count(zweitimpfung) AS \"zweit\"\nFROM gemeinde_impfungen\nWHERE\n  1=1\n  AND $__timeFilter(zweitimpfung)\nGROUP BY time\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(registration,$__interval),\n  count(registration) AS \"registration\"\nFROM gemeinde_impfungen\nWHERE\n  1=1\n  AND $__timeFilter(registration)\nGROUP BY time\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Erst-Impfungen pro Angebot Typ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(erstimpfung,$__interval),\n  erstimpfung_odi_typ as Angebot,\n  count(erstimpfung_odi_typ)\nFROM gemeinde_impfungen\nWHERE\n  1=1\n  AND $__timeFilter(erstimpfung)\nGROUP BY erstimpfung, erstimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Zweit-Impfungen pro Angebot Typ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(zweitimpfung,$__interval),\n  zweitimpfung_odi_typ as Angebot,\n  count(zweitimpfung_odi_typ)\nFROM gemeinde_impfungen\nWHERE\n  1=1\n  AND $__timeFilter(zweitimpfung)\nGROUP BY zweitimpfung, zweitimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Variable Siedlungsgebiet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Erst-Impfungen pro Angebot Typ in Gemeinden mit < $siedlungsgebiet km^2 Siedlungsgebiet",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(gi.erstimpfung,$__interval),\n  gi.erstimpfung_odi_typ as Angebot,\n  count(gi.erstimpfung_odi_typ)\nFROM gemeinde_impfungen gi, gemeinde_portrait gp\nWHERE\n  gp.gemeinde_name = gi.wohngemeinde\n  AND $__timeFilter(erstimpfung)\n  AND gp.flaeche_siedlung < $siedlungsgebiet\nGROUP BY gi.erstimpfung, gi.erstimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Erst-Impfungen pro Angebot Typ in Gemeinden mit > $siedlungsgebiet km^2 Siedlungsgebiet",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(gi.erstimpfung,$__interval),\n  gi.erstimpfung_odi_typ as Angebot,\n  count(gi.erstimpfung_odi_typ)\nFROM gemeinde_impfungen gi, gemeinde_portrait gp\nWHERE\n  gp.gemeinde_name = gi.wohngemeinde\n  AND $__timeFilter(erstimpfung)\n  AND gp.flaeche_siedlung > $siedlungsgebiet\nGROUP BY gi.erstimpfung, gi.erstimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Variable Bevoelkerungsdichte",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Erst-Impfungen pro Angebot Typ in Gemeinden mit < $bev_dichte Bevölkerungsdichte",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(gi.erstimpfung,$__interval),\n  gi.erstimpfung_odi_typ as Angebot,\n  count(gi.erstimpfung_odi_typ)\nFROM gemeinde_impfungen gi, gemeinde_portrait gp\nWHERE\n  gp.gemeinde_name = gi.erstimpfung_gemeinde\n  AND $__timeFilter(erstimpfung)\n  AND gp.bevoelkerung_bevoelkerungsdichte < $bev_dichte\nGROUP BY gi.erstimpfung, gi.erstimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Erst-Impfungen pro Angebot Typ in Gemeinden mit > $bev_dichte Bevölkerungsdichte",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(gi.erstimpfung,$__interval),\n  gi.erstimpfung_odi_typ as Angebot,\n  count(gi.erstimpfung_odi_typ)\nFROM gemeinde_impfungen gi, gemeinde_portrait gp\nWHERE\n  gp.gemeinde_name = gi.erstimpfung_gemeinde\n  AND $__timeFilter(erstimpfung)\n  AND gp.bevoelkerung_bevoelkerungsdichte > $bev_dichte\nGROUP BY gi.erstimpfung, gi.erstimpfung_odi_typ\nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}