{
 "title": "inzidenz",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Impfrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(erstimpfung,$__interval),\n  count(erstimpfung) AS \"erst\"\nFROM gemeinde_impfungen\nWHERE\n  $__timeFilter(erstimpfung)\n  AND vollstaendiger_impfschutz = 'Y'\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(zweitimpfung,$__interval),\n  count(zweitimpfung) AS \"zweit\"\nFROM gemeinde_impfungen\nWHERE\n  $__timeFilter(zweitimpfung) \n  AND vollstaendiger_impfschutz = 'Y'\nGROUP BY time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(registration,$__interval),\n  count(registration) AS \"registration\"\nFROM gemeinde_impfungen\nWHERE\n  $__timeFilter(registration)\n  AND vollstaendiger_impfschutz = 'Y'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Impfrate nach Impfgruppen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(erstimpfung,$__interval),\n  count(imfgruppe) AS \"G:\",\n  imfgruppe\nFROM gemeinde_impfungen\nWHERE\n  $__timeFilter(erstimpfung)\n  AND vollstaendiger_impfschutz = 'Y'\nGROUP BY time, imfgruppe\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"<10\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.bevoelkerung_auslaender < 10\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datum,$__interval),\n  avg(gi.inzidenz) AS \"stadt\"\nFROM gemeinde_inzidenzen gi, gemeinde_portrait gp\nWHERE\n  gi.bfs_nummer = gp.bfs_nummer\n  AND gp.bevoelkerung_auslaender >= 10\n  AND $__timeFilter(gi.datum)\nGROUP BY time\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Impfdistanz Pro Gemeinde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gi.erstimpfung,$__interval),\n  max(gdist(gi.wohngemeinde, gi.erstimpfung_gemeinde))/1000 AS \"Distance\"\nFROM gemeinde_impfungen gi\nWHERE\n  $__timeFilter(gi.erstimpfung)\n  AND gi.vollstaendiger_impfschutz = 'Y'\nGROUP By gi.erstimpfung\nORDER BY 1"
    }
   ]
  }
 ]
}